darknet_ros:
  ros__parameters:
    yolo_model:
      config_file:
        name: yolov4-tiny-gostop.cfg
      weight_file:
        name: yolov4-tiny-gostop.weights
      threshold:
        value: 0.6
      detection_classes:
        names:
          - stop
          - go
          - right
          - left