darknet_ros:
  ros__parameters:
    yolo_model:
      config_file:
        name: yolov4-tiny-gostop.cfg
      weight_file:
        name: yolov4-tiny-gostop.weights
      threshold:
        value: 0.3
      detection_classes:
        names:
          - go
          - stop
          - left
          - right