darknet_ros:
  ros__parameters:
    yolo_model:
      config_file:
        name: yolov4-tiny-moniarm.cfg
      weight_file:
        name: yolov4-tiny-moniarm.weights
      threshold:
        value: 0.9
      detection_classes:
        names:
        - watermelon
        - grape
        - pineapple
